server:
  port: 8084

spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 10
      max-wait: 10000
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
  redis:
    host: localhost
    port: 6379
    pool.max-idle: 8
    pool.min-idle: 0
    pool.max-active: 8
    pool.max-wait: -1
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2669344359@qq.com
    password: umakpitmsmuudjgh
    port: 25
    protocol: smtp
    properties:
       mail:
          smtp:
             auth: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

  #Eureka
  eureka:
    client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/

  #logging
  logging:
    level: debug

